### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AntDavidLima** [AntDavidLima/loomer-imoveis#1]
- [x] Definir o roadmap da aplicação
 - [x] Definir quais tecnologias utilizar
 - [x] Definir o esquema do banco de dados
 - [ ] Escrever um README
 ---
 - [ ] Usuários
   - [ ] CRUD
   - [ ] Autenticação JWT
   - [ ] Criptografia de senhas
 - [ ] Imóveis
   - [ ] CRUD
   - [ ] Permitir que apenas usuários cadastrado execute ações com os imóveis
