### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AntDavidLima** [AntDavidLima/loomer-imoveis#1]
- [ ] Definir o roadmap da aplicação
 - [ ] Definir quais tecnologias utilizar
 - [ ] Definir o esquema do banco de dados
 ---
 - [ ] Usuários
   - [ ] CRUD
   - [ ] Autenticação JWT
   - [ ] Criptografia de senhas
 - [ ] Imóveis
   - [ ] CRUD
   - [ ] Permitir que apenas usuários cadastrado execute ações com os imóveis
