### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AntDavidLima** [AntDavidLima/loomer-imoveis#1]
- [x] Definir o roadmap da aplicação
 - [x] Definir quais tecnologias utilizar
 - [x] Definir o esquema do banco de dados
 - [x] Escrever um README
 ---
 - [x] Usuários
   - [x] Cadastro
   - [x] Autenticação
   - [x] Criptografia de senhas
 - [x] Imóveis
   - [x] CRUD
   - [x] Permitir que apenas usuários cadastrado execute ações com os imóveis
